### ISSUE TITLE
category id

### ISSUE THREAD

**Issue by Yan0613** [CV-Altrai2023/RailFOD23#2]
what's the category id of the json file represents for? I can't find the related files about mapping of category numbers and specific meanings. Could you provide any useful information? Thank you!

**Comment by CV-Altrai2023** [comment]
Thank you for your interest in our dataset. The category ids can be found in the json file under "categories". Since github is linked to an uncommon email address. You can visit the common email "fengzhichengai@163.com" so that I can reply in time..

**Comment by Yan0613** [comment]
I can see the category id in the json file, however, I don't know the number represents for which object, such asa a balloon. Could you provide some information? Thank you very much!

**Comment by yang762** [comment]
> I can see the category id in the json file, however, I don't know the number represents for which object, such asa a balloon. Could you provide some information? Thank you very much!

1:Nest
2:Plastic bag
3:Fluttering object
4:Balloon
